version: "3.6"
networks:
  default:
    external:
      name: symf_sbmd_app
services:

  sbmd_symf_platform_nginx:
    image: nginx:latest
    container_name: sbmd_symf_platform_nginx
    volumes:
      - ./developer/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - sbmd_symf_platform_php
    ports:
    - 80:80

  sbmd_symf_platform_php:
    image: php:7.4-fpm
    container_name: sbmd_symf_platform_php
    build:
      context: ./
      dockerfile: ./developer/Dockerfile
    working_dir: /app
    volumes:
      - ./app/:/app
